import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";
import SessionProviders from "@/context/session-provider";
import QueryProvider from "@/context/query-provider";

const dmSans = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "X-Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(`bg-background`, dmSans.className)}>
        <SessionProviders>
          <QueryProvider>
            {children}
            <Toaster />
          </QueryProvider>
        </SessionProviders>
      </body>
    </html>
  );
}
